### ISSUE TITLE
java.lang.BootstrapMethodError under -controlTrack

### ISSUE THREAD

**Issue by BihuanChen** [Programming-Systems-Lab/phosphor#20]
Hello,

I was trying to run the following program with the flag `-controlTrack` enabled.
```java
public class Test {
	
	public static void main(String[] args) throws IOException, ClassNotFoundException {
		File f = new File("/home/bhchen/Desktop/msg");
		if (f.exists()) { f.delete(); }
		
        ObjectOutputStream oot = new ObjectOutputStream(new FileOutputStream("/home/bhchen/Desktop/msg"));
        oot.writeInt(11);
        oot.close();
        		
		ObjectInputStream ois = new ObjectInputStream(new FileInputStream("/home/bhchen/Desktop/msg"));
		int obj = ois.readInt();
		System.out.println(obj);
		ois.close();
	}

}
```
Phosphor (the current head) threw the following exception.
```java
Exception in thread "main" java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Error.<init>(Error.java:88)
	at java.lang.LinkageError.<init>(LinkageError.java:67)
	at java.lang.BootstrapMethodError.<init>(BootstrapMethodError.java:66)
	at java.lang.invoke.CallSite.makeSite$$PHOSPHORTAGGED(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl$$PHOSPHORTAGGED(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite$$PHOSPHORTAGGED(MethodHandleNatives.java:297)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java)
	at java.io.ObjectInputStream.<clinit>(ObjectInputStream.java:3578)
	at chronicle.test.Test.main$$PHOSPHORTAGGED(Test.java:50)
	at chronicle.test.Test.main(Test.java)
Caused by: java.lang.invoke.LambdaConversionException: Type mismatch in captured lambda parameter 0: expecting class edu.columbia.cs.psl.phosphor.struct.ControlTaintTagStack, found class java.io.ObjectInputStream
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.invoke.LambdaConversionException.<init>(LambdaConversionException.java:45)
	at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs$$PHOSPHORTAGGED(AbstractValidatingLambdaMetafactory.java:256)
	at java.lang.invoke.LambdaMetafactory.metafactory$$PHOSPHORTAGGED(LambdaMetafactory.java:303)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java)
	at java.lang.invoke.CallSite.makeSite$$PHOSPHORTAGGED(CallSite.java:302)
	... 6 more
```
However, if the flag `-controlTrack` was disabled, Phosphor worked well.

I found a similar issue https://github.com/Programming-Systems-Lab/phosphor/issues/3, but it failed in my case. It seems this results from the `MultiTaint` mode as `MultiTaint` mode is enabled automatically under `controlTrack`. Please help to have a look.

Thanks,
Bihuan

**Comment by jon-bell** [comment]
Can I have the output of java -version ?

**Comment by BihuanChen** [comment]
Hi Jon,

I am using HotSpot 1.8.0_91-b14, 64-bit version.

**Comment by jon-bell** [comment]
While I am working through this (it's going to be a bit of a while - I am on vacation until Aug 9 but will try to poke around at it before I get back), are you OK with using an older ( 1.8.0 <= u66) version of Java?

**Comment by BihuanChen** [comment]
Ok. Thanks, Jon.

**Comment by BihuanChen** [comment]
It seems the problem remains for the new java version...
```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by jon-bell** [comment]
Was this not fixed on Jul 25 or did it regress?

**Comment by BihuanChen** [comment]
It regressed.

**Comment by jon-bell** [comment]
I'm not able to reproduce.
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

I added a test case based on the code above in e7ce551. Does this test pass in your environment? If so, what is a failing test case?

**Comment by BihuanChen** [comment]
This is strange. The test case above failed on my machine.
Did you enable the `controlTrack` flag?

**Comment by jon-bell** [comment]
Yes. You are running the test with mvn verify?

**Comment by BihuanChen** [comment]
The `GeneralImplicitITCase` passed with mvn install, but failed when using cmd lines...

```java
Exception in thread "main" java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Error.<init>(Error.java:88)
	at java.lang.LinkageError.<init>(LinkageError.java:67)
	at java.lang.BootstrapMethodError.<init>(BootstrapMethodError.java:66)
	at java.lang.invoke.CallSite.makeSite$$PHOSPHORTAGGED(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl$$PHOSPHORTAGGED(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite$$PHOSPHORTAGGED(MethodHandleNatives.java:297)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java)
	at java.io.ObjectInputStream.<clinit>(ObjectInputStream.java:3578)
	at phosphor.test.Test2.main$$PHOSPHORTAGGED(Test2.java:20)
	at phosphor.test.Test2.main(Test2.java)
Caused by: java.lang.AbstractMethodError: java.lang.invoke.BoundMethodHandle.fieldCount$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/struct/ControlTaintTagStack;Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag;)Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag;
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at java.lang.LinkageError.<init>(LinkageError.java:55)
	at java.lang.IncompatibleClassChangeError.<init>(IncompatibleClassChangeError.java:55)
	at java.lang.AbstractMethodError.<init>(AbstractMethodError.java:56)
	at java.lang.AbstractMethodError.<init>(AbstractMethodError.java)
	at java.lang.invoke.BoundMethodHandle.tooComplex$$PHOSPHORTAGGED(BoundMethodHandle.java:127)
	at java.lang.invoke.BoundMethodHandle.rebind$$PHOSPHORTAGGED(BoundMethodHandle.java:120)
	at java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor$$PHOSPHORTAGGED(MethodHandleImpl.java:232)
	at java.lang.invoke.MethodHandleImpl.makePairwiseConvert$$PHOSPHORTAGGED(MethodHandleImpl.java:194)
	at java.lang.invoke.MethodHandleImpl.makePairwiseConvert$$PHOSPHORTAGGED(MethodHandleImpl.java:380)
	at java.lang.invoke.MethodHandle.asTypeUncached$$PHOSPHORTAGGED(MethodHandle.java:776)
	at java.lang.invoke.MethodHandle.asType$$PHOSPHORTAGGED(MethodHandle.java:761)
	at java.lang.invoke.Invokers.checkGenericType$$PHOSPHORTAGGED(Invokers.java:321)
	at java.lang.invoke.Invokers.checkGenericType(Invokers.java)
	at java.lang.invoke.CallSite.makeSite$$PHOSPHORTAGGED(CallSite.java:302)
	... 6 more
```

**Comment by jon-bell** [comment]
So how are you running it? Can I have exact steps to reproduce?

**Comment by BihuanChen** [comment]
Here are the exact steps.

Instrument the jre
```java
java -jar Phosphor-0.0.2-SNAPSHOT.jar -controlTrack /usr/lib/jvm/java-8-oracle/jre jre-inst-p-cf
chmod +x jre-inst-p-cf/bin/*
````

Instrument the target program
```java
java -jar Phosphor-0.0.2-SNAPSHOT.jar -controlTrack phosphor-test.jar lib-inst-p-cf
```

Run the target program
```java
jre-inst-p-cf/bin/java -Xbootclasspath/a:Phosphor-0.0.2-SNAPSHOT.jar -cp lib-inst-p-cf/phosphor-test.jar phosphor.test.Test2
```

And get the exception...
```java
Exception in thread "main" java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Error.<init>(Error.java:88)
	at java.lang.LinkageError.<init>(LinkageError.java:67)
	at java.lang.BootstrapMethodError.<init>(BootstrapMethodError.java:66)
	at java.lang.invoke.CallSite.makeSite$$PHOSPHORTAGGED(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl$$PHOSPHORTAGGED(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite$$PHOSPHORTAGGED(MethodHandleNatives.java:297)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java)
	at java.io.ObjectInputStream.<clinit>(ObjectInputStream.java:3578)
	at phosphor.test.Test2.main$$PHOSPHORTAGGED(Test2.java:20)
	at phosphor.test.Test2.main(Test2.java)
Caused by: java.lang.AbstractMethodError: java.lang.invoke.BoundMethodHandle.fieldCount$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/struct/ControlTaintTagStack;Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag;)Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag;
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at java.lang.LinkageError.<init>(LinkageError.java:55)
	at java.lang.IncompatibleClassChangeError.<init>(IncompatibleClassChangeError.java:55)
	at java.lang.AbstractMethodError.<init>(AbstractMethodError.java:56)
	at java.lang.AbstractMethodError.<init>(AbstractMethodError.java)
	at java.lang.invoke.BoundMethodHandle.tooComplex$$PHOSPHORTAGGED(BoundMethodHandle.java:127)
	at java.lang.invoke.BoundMethodHandle.rebind$$PHOSPHORTAGGED(BoundMethodHandle.java:120)
	at java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor$$PHOSPHORTAGGED(MethodHandleImpl.java:232)
	at java.lang.invoke.MethodHandleImpl.makePairwiseConvert$$PHOSPHORTAGGED(MethodHandleImpl.java:194)
	at java.lang.invoke.MethodHandleImpl.makePairwiseConvert$$PHOSPHORTAGGED(MethodHandleImpl.java:380)
	at java.lang.invoke.MethodHandle.asTypeUncached$$PHOSPHORTAGGED(MethodHandle.java:776)
	at java.lang.invoke.MethodHandle.asType$$PHOSPHORTAGGED(MethodHandle.java:761)
	at java.lang.invoke.Invokers.checkGenericType$$PHOSPHORTAGGED(Invokers.java:321)
	at java.lang.invoke.Invokers.checkGenericType(Invokers.java)
	at java.lang.invoke.CallSite.makeSite$$PHOSPHORTAGGED(CallSite.java:302)
	... 6 more
```

**Comment by jon-bell** [comment]
This is not a regression. We instrument dynamically generated classes (like those generated to support lambdas) using a JavaAgent. You need to add the javaagent to your launch string... -javaagent:Phosphor-0.0.2-SNAPSHOT.jar.

**Comment by BihuanChen** [comment]
aha, that solves the problem... Thanks.
