### ISSUE TITLE
java.lang.BootstrapMethodError: call site initialization exception

### ISSUE THREAD

**Issue by ytang** [Programming-Systems-Lab/phosphor#3]
Hello,

I was trying to run the following program:

```
public class Main {
    public static void main(String[] args) {
        Runnable r = () -> {};
    }
}
```

Phosphor (current HEAD, e96fe8a0c32e3e3339fe7b485408bf54041220d1) threw the following exception on both OpenJDK 1.8.0_65 and Oracle Java 1.8.0_66:

```
Exception in thread "main" java.lang.BootstrapMethodError: call site initialization exception
        at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
        at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
        at Main.main(Main.java:3)
Caused by: java.lang.AbstractMethodError: java.lang.invoke.BoundMethodHandle.fieldCount$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag;)Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag;
        at java.lang.invoke.BoundMethodHandle.tooComplex$$PHOSPHORTAGGED(BoundMethodHandle.java:125)
        at java.lang.invoke.BoundMethodHandle.rebind(BoundMethodHandle.java:118)
        at java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor$$PHOSPHORTAGGED(MethodHandleImpl.java:232)
        at java.lang.invoke.MethodHandleImpl.makePairwiseConvert$$PHOSPHORTAGGED(MethodHandleImpl.java:194)
        at java.lang.invoke.MethodHandleImpl.makePairwiseConvert$$PHOSPHORTAGGED(MethodHandleImpl.java:380)
        at java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:776)
        at java.lang.invoke.MethodHandle.asType(MethodHandle.java:761)
        at java.lang.invoke.Invokers.checkGenericType(Invokers.java:321)
        at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
        ... 3 more
```

Could you please take a look?

**Comment by jon-bell** [comment]
Hi Yang,
Still having a lot of trouble reproducing this. I added a test case for this (`edu.columbia.cs.psl.test.phosphor.LambdaIntTagITCase`) and it passes when run on my local mac (hotspot 1.8.0_66) and on my linux server (openjdk 1.8.0_65) and [on travis](https://travis-ci.org/Programming-Systems-Lab/phosphor/builds/97559476) (hotspot 1.8.0_31). Can you try running the test case and see if that works?

You can run just the int-tag tests by running `mvn -DskipIntTagNoInstTests=true -DskipObjTagTests=true -DskipImplicitTests=true verify` (if it doesn't exist, this will also cause instrumented JREs to be generated under the target/ directory, so make sure JAVA_HOME is set correctly before running it, because that's the JRE that gets instrumented).

**Comment by ytang** [comment]
Hi Jon,

Thanks for adding the test case. It amazingly passes for me! I find that if I add `-javaagent:Phosphor-0.0.2-SNAPSHOT.jar` and disable `-multiTaint`, then my program also runs fine. However, if I enable `-multiTaint`, my program crashes:

```
Exception in thread "main" java.lang.BootstrapMethodError: call site initialization exception
        at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
        at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
        at Main.main(Main.java:3)
Caused by: java.lang.NoClassDefFoundError: Main$$Lambda$1
        at sun.misc.Unsafe.defineAnonymousClass(Native Method)
        at sun.misc.Unsafe.defineAnonymousClass$$PHOSPHORTAGGED(Unsafe.java)
        at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:326)
        at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:194)
        at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:304)
        at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: Main$$Lambda$1
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass$$PHOSPHORTAGGED(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass$$PHOSPHORTAGGED(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 9 more
```

**Comment by jon-bell** [comment]
This should now be fixed.

**Comment by ytang** [comment]
Thank you so much for your swift action, Jon! Would you also update `README.md` to reflect the required option `-javaagent` please?

**Comment by jon-bell** [comment]
Yeah, thanks - updated the docs.
