### ISSUE TITLE
Serialization problem

### ISSUE THREAD

**Issue by mikefhsu** [Programming-Systems-Lab/phosphor#34]
If I use a serialization lib, such as xstream, to clone an array, I will have the following exception:
`java.lang.NullPointerException 
at edu.columbia.cs.psl.phosphor.runtime.ArrayReflectionMasker.getInt$$PHOSPHORTAGGED(ArrayReflectionMasker.java:717) ~[?:?]
at edu.columbia.cs.psl.phosphor.runtime.ArrayReflectionMasker.get$$PHOSPHORTAGGED(ArrayReflectionMasker.java:480) ~[?:?]
at com.thoughtworks.xstream.converters.collections.ArrayConverter.marshal(ArrayConverter.java:44) `

You can find my test file in the txt file (sorry, .java is not accepted). The error is from xstream.toXML.
[SerializationTest.txt](https://github.com/Programming-Systems-Lab/phosphor/files/491935/SerializationTest.txt)

Thanks.

**Comment by jon-bell** [comment]
Should be fixed now.
