### ISSUE TITLE
Expected result of sample project

### ISSUE THREAD

**Issue by pbandyop** [Programming-Systems-Lab/phosphor#39]
Hello,

so I tried to play-around a bit with Phosphor. All the steps executed as it is provided in the `README` file expect for the example project. Whenever, I provide the following command:

`XYZ-computer:target payel$ jre-inst/bin/java -Xbootclasspath/a:Phosphor-0.0.3-SNAPSHOT.jar -javaagent:Phosphor-0.0.3-SNAPSHOT.jar -cp inst/phosphortests.jar -ea phosphor.test.DroidBenchTest`

As, it is specified in the README file, I am running all the commands (including the above command) from **target** directory of Phosphor project.

then I get the **below result**. Can you let me know if the result is correct i.e. it shows **a list of test cases, with assertion errors for each "testImplicitFlow" test case.**

`objc[8233]: Class JavaLaunchHelper is implemented in both /Users/payel/Documents/FreshPhosphorLookMarch/phosphor/Phosphor/target/jre-inst/bin/java and /Users/payel/Documents/FreshPhosphorLookMarch/phosphor/Phosphor/target/jre-inst/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
testFieldSensitivity1
testFieldSensitivity2
testFieldSensitivity3
testFieldSensitivity4
testInheritedObjects1
testObjectSensitivity1
testObjectSensitivity2
testExceptions1
testExceptions2
testExceptions3
testExceptions4
testLoopExample1
testLoopExample2
testSourceCodeSpecific1
testStaticInitialization1
testStaticInitialization2
testUnreachableCode
testImplicitFlow1
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at phosphor.test.DroidBenchTest.main(DroidBenchTest.java:521)
Caused by: java.lang.AssertionError
	at phosphor.test.DroidBenchTest$ImplicitFlow1.writeToLog(DroidBenchTest.java:361)
	at phosphor.test.DroidBenchTest$ImplicitFlow1.doTest(DroidBenchTest.java:294)
	at phosphor.test.DroidBenchTest.testImplicitFlow1(DroidBenchTest.java:366)
	... 5 more
testImplicitFlow2
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at phosphor.test.DroidBenchTest.main(DroidBenchTest.java:521)
Caused by: java.lang.AssertionError
	at phosphor.test.DroidBenchTest.testImplicitFlow2(DroidBenchTest.java:375)
	... 5 more
testImplicitFlow3
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at phosphor.test.DroidBenchTest.main(DroidBenchTest.java:521)
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to edu.columbia.cs.psl.phosphor.struct.TaintedWithObjTag
	at phosphor.test.DroidBenchTest$ImplicitFlow3.doTest(DroidBenchTest.java:270)
	at phosphor.test.DroidBenchTest.testImplicitFlow3(DroidBenchTest.java:379)
	... 5 more
testImplicitFlow4
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at phosphor.test.DroidBenchTest.main(DroidBenchTest.java:521)
Caused by: java.lang.AssertionError
	at phosphor.test.DroidBenchTest$ImplicitFlow4.doTest(DroidBenchTest.java:253)
	at phosphor.test.DroidBenchTest.testImplicitFlow4(DroidBenchTest.java:383)
	... 5 more
testArrayAccess1
testArrayAccess2
testHashMapAccess1
testListAccess1
testReflectionTest1
testReflectionTest2
testReflectionTest3
testReflectionTest4
`
Please let me know if I am getting the correct result. I am absolutely new and a bit confused on the expected output. 

Thanks!

**Comment by jon-bell** [comment]
Hi,
Sorry about this - I should update the documentation. Please don't use the PhosphorTests project - it's fallen out of maintenance. The DroidBench example is now an integration test and will run automatically with `mvn verify`.

**Comment by pbandyop** [comment]
Hello,

I updated my issue. I think I was using the command in a wrong way. What I was doing was:

`$ JAVA_HOME=jre-inst/ $JAVA_HOME/bin/java -Xbootclasspath/a:Phosphor-0.0.3-SNAPSHOT.jar -javaagent:Phosphor-0.0.3-SNAPSHOT.jar -cp inst/phosphortests.jar -ea phosphor.test.DroidBenchTest`

My computer was unable to interpret JAVA_HOME. Hence, I did the below and it worked I guess.
`target payel$ jre-inst/bin/java -Xbootclasspath/a:Phosphor-0.0.3-SNAPSHOT.jar -javaagent:Phosphor-0.0.3-SNAPSHOT.jar -cp inst/phosphortests.jar -ea phosphor.test.DroidBenchTest`

Can you check my output (in my updated issue) and let me know if that is what I am about to expect.

**Comment by jon-bell** [comment]
You can run it with mvn verify and see what it should be.

**Comment by pbandyop** [comment]
So, if I want to run Phosphor with a sample project of mine, then how do I run it? Using, "mvn verify" kind of restricts me to higher level. I am unable to track down, as to how to use Phosphor tool for my sample java project. 

Any pointers will be helpful. 

Thanks!

**Comment by jon-bell** [comment]
The absolute easiest way is to just use Phosphor as a javaagent. It will only require you to instrument the JRE, then when you run your app, use the instrumented JRE, and add to your command:
`-Xbootclasspath/a:Phosphor-0.0.3-SNAPSHOT.jar -javaagent:Phosphor-0.0.3-SNAPSHOT.jar=cacheDir=phosphorCache` (correcting the paths to phosphor).

**Comment by jon-bell** [comment]
Please let me know if you have any more questions or have suggestions to improve the documentation.
