### ISSUE TITLE
Exception in instrumenting JRE with controlTrack flag

### ISSUE THREAD

**Issue by davidchen19** [Programming-Systems-Lab/phosphor#44]
Hello,
When I instrumented the jre with control track flag, it threw an exception. However, if I removed the control track flag, the instrumentation was successful.

My jdk environment is 

```
> java version "1.8.0_131"
> Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
The process of instrumentation is 
1)generate Phosphor-0.0.3-SNAPSHOT.jar
`mvn package`

2)instrument jre
`java -jar Phosphor-0.0.3-SNAPSHOT.jar -controlTrack /usr/lib/jvm/jdk1.8.0_131/jre jre-inst`

However, the exception comes
```
Processed: 24000/31566
Processed: 25000/31566
Processed: 26000/31566
edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 57: Incompatible stack heights
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.analysis.Analyzer.analyze(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.util.CheckMethodAdapter$1.visitEnd(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.util.CheckMethodAdapter.visitEnd(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.b(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer._transform(PreMain.java:317)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:161)
	at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:195)
	at edu.columbia.cs.psl.phosphor.Instrumenter.processZip(Instrumenter.java:620)
	at edu.columbia.cs.psl.phosphor.Instrumenter.processDirectory(Instrumenter.java:565)
	at edu.columbia.cs.psl.phosphor.Instrumenter.processDirectory(Instrumenter.java:561)
	at edu.columbia.cs.psl.phosphor.Instrumenter._main(Instrumenter.java:514)
	at edu.columbia.cs.psl.phosphor.Instrumenter.main(Instrumenter.java:404)
Caused by: edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.analysis.AnalyzerException: Incompatible stack heights
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.analysis.Frame.merge(Frame.java:687)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.analysis.Analyzer.merge(Unknown Source)
	... 15 more

```
Before that I think my jdk environment maybe has some problem, so I change my jdk enviroment from `openjdk-8-amd64 `to `jdk1.8.0_131`. However, both of them have the problem. If I don't use the control track flag, it success like that. But I need control flow tracking.
```
Processed: 27000/31566
Processed: 28000/31566
Processed: 29000/31566
Processed: 30000/31566
Processed: 31000/31566
Done after 115665 ms
```

Any help will be appreciated. Thanks!

**Comment by flakycov** [comment]
Ouch - it looks like this is on Travis too (and not throwing an alert for some reason). I will try to patch this up later today.

**Comment by jon-bell** [comment]
Ouch - it looks like this is on Travis too (and not throwing an alert for some reason). I will try to patch this up later today.

**Comment by jon-bell** [comment]
This should be fixed now in the latest commit

**Comment by davidchen19** [comment]
Thanks a lot. The latest commit version did fix the problem. However, when I instrumented the code `weka.jar` that I wanted to taint, the `Method code too large` exception arose like this.
```
Processed: 1000/5124
Processed: 2000/5124
Processed: 3000/5124
java.lang.RuntimeException: Method code too large!
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodWriter.a(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer._transform(PreMain.java:316)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:161)
	at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:195)
	at edu.columbia.cs.psl.phosphor.Instrumenter.processZip(Instrumenter.java:620)
	at edu.columbia.cs.psl.phosphor.Instrumenter._main(Instrumenter.java:516)
	at edu.columbia.cs.psl.phosphor.Instrumenter.main(Instrumenter.java:404)
java.lang.RuntimeException: Method code too large!
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodWriter.a(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer._transform(PreMain.java:316)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:161)
	at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:195)
	at edu.columbia.cs.psl.phosphor.Instrumenter.processZip(Instrumenter.java:620)
	at edu.columbia.cs.psl.phosphor.Instrumenter._main(Instrumenter.java:516)
	at edu.columbia.cs.psl.phosphor.Instrumenter.main(Instrumenter.java:404)
method so far:
Saving org/netlib/lapack/Dgesvd
java.lang.RuntimeException: Method code too large!
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.MethodWriter.a(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer._transform(PreMain.java:316)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:161)
	at edu.columbia.cs.psl.phosphor.Instrumenter.instrumentClass(Instrumenter.java:195)
	at edu.columbia.cs.psl.phosphor.Instrumenter.processZip(Instrumenter.java:620)
	at edu.columbia.cs.psl.phosphor.Instrumenter._main(Instrumenter.java:516)
	at edu.columbia.cs.psl.phosphor.Instrumenter.main(Instrumenter.java:404)
```
Methods of weka in Java are already quite large, and instrumenting them increases their size further causing the exception(the JVM imposes a size of 65535 bytes on the size of any method). I think the only way is splitting the offending methods but I don't know where the method is. The information of exception was all related to phosphor but not weka. Can phosphor store or output the information of the certain implemented  method like name or location?

**Comment by jon-bell** [comment]
Yes - the control flow tracking adds a LOT of instrumentation, and much code that works with Phosphor's data flow tracking succumbs to this problem when adding the control flow tracking.

The class that caused the problem was `org.netlib.lapack.Dgesvd`. Phosphor should have created a file, `lastClass.txt` with a text version of the instrumented class, and you can see for yourself which method caused the problem.

**Comment by davidchen19** [comment]
I got it! I’m much obliged.
