### ISSUE TITLE
Error Processing Annotations With Parameters 

### ISSUE THREAD

**Issue by jsinglet** [Programming-Systems-Lab/phosphor#48]
If one creates an annotation with the following definition and uses it you get an ArrayAccessException. If the annotation is *not* present in the class file this error goes away (i.e., a different retention policy). 

```java
@Retention(RUNTIME)
@Target({ TYPE, FIELD, METHOD, PARAMETER, CONSTRUCTOR, LOCAL_VARIABLE, ANNOTATION_TYPE, PACKAGE, TYPE_PARAMETER,
		TYPE_USE })
public @interface MyAnnotation {
	 String[] value();
}
```

```
java.lang.ArrayStoreException
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.lang.RuntimeException.<init>(RuntimeException.java:51)
	at java.lang.ArrayStoreException.<init>(ArrayStoreException.java:48)
	at java.lang.ArrayStoreException.<init>(ArrayStoreException.java)
	at java.lang.System.arraycopy(Native Method)
	at edu.columbia.cs.psl.phosphor.TaintUtils.arraycopy(TaintUtils.java:526)
	at java.util.ArrayList.toArray$$PHOSPHORTAGGED(ArrayList.java:408)
	at java.util.ArrayList.toArray(ArrayList.java)
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visitAnnotations(TaintTrackingClassVisitor.java:1367)
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visitEnd(TaintTrackingClassVisitor.java:879)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.SerialVersionUIDAdder.visitEnd(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer._transform(PreMain.java:310)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:162)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform$$PHOSPHORTAGGED(PreMain.java:138)
	at sun.instrument.TransformerManager.transform$$PHOSPHORTAGGED(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform$$PHOSPHORTAGGED(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass1$$PHOSPHORTAGGED(ClassLoader.java)
	at java.lang.ClassLoader.defineClass$$PHOSPHORTAGGED(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass$$PHOSPHORTAGGED(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass$$PHOSPHORTAGGED(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100$$PHOSPHORTAGGED(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run$$PHOSPHORTAGGED(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run$$PHOSPHORTAGGED(URLClassLoader.java:362)
	at java.net.URLClassLoader$1.run(URLClassLoader.java)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged$$PHOSPHORTAGGED(AccessController.java)
	at java.net.URLClassLoader.findClass$$PHOSPHORTAGGED(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass$$PHOSPHORTAGGED(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass$$PHOSPHORTAGGED(Launcher.java:331)
	at java.lang.ClassLoader.loadClass$$PHOSPHORTAGGED(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain$$PHOSPHORTAGGED(LauncherHelper.java:495)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java)
java.lang.ArrayStoreException
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.lang.RuntimeException.<init>(RuntimeException.java:51)
	at java.lang.ArrayStoreException.<init>(ArrayStoreException.java:48)
	at java.lang.ArrayStoreException.<init>(ArrayStoreException.java)
	at java.lang.System.arraycopy(Native Method)
	at edu.columbia.cs.psl.phosphor.TaintUtils.arraycopy(TaintUtils.java:526)
	at java.util.ArrayList.toArray$$PHOSPHORTAGGED(ArrayList.java:408)
	at java.util.ArrayList.toArray(ArrayList.java)
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visitAnnotations(TaintTrackingClassVisitor.java:1367)
	at edu.columbia.cs.psl.phosphor.instrumenter.TaintTrackingClassVisitor.visitEnd(TaintTrackingClassVisitor.java:879)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.commons.SerialVersionUIDAdder.visitEnd(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassReader.accept(Unknown Source)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer._transform(PreMain.java:310)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform(PreMain.java:162)
	at edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer.transform$$PHOSPHORTAGGED(PreMain.java:138)
	at sun.instrument.TransformerManager.transform$$PHOSPHORTAGGED(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform$$PHOSPHORTAGGED(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass1$$PHOSPHORTAGGED(ClassLoader.java)
	at java.lang.ClassLoader.defineClass$$PHOSPHORTAGGED(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass$$PHOSPHORTAGGED(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass$$PHOSPHORTAGGED(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100$$PHOSPHORTAGGED(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run$$PHOSPHORTAGGED(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run$$PHOSPHORTAGGED(URLClassLoader.java:362)
	at java.net.URLClassLoader$1.run(URLClassLoader.java)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged$$PHOSPHORTAGGED(AccessController.java)
	at java.net.URLClassLoader.findClass$$PHOSPHORTAGGED(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass$$PHOSPHORTAGGED(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass$$PHOSPHORTAGGED(Launcher.java:331)
	at java.lang.ClassLoader.loadClass$$PHOSPHORTAGGED(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain$$PHOSPHORTAGGED(LauncherHelper.java:495)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java)

```

**Comment by jsinglet** [comment]
A note: this is only a problem if only applies the annotation to a LOCAL variable. Fields appear to be fine as well as method parameters.

**Comment by jon-bell** [comment]
Maybe can you add this in the form of a test case - in your own branch or in a PR?

**Comment by jsinglet** [comment]
Sure, I'll add it. I'm rebuilding clean now. I should add this seems to only happen in the implicit variant of the JVM.

**Comment by jon-bell** [comment]
Thanks & Sorry - I was unnecessarily copying local var annotations when generating wrappers for methods - stupid, because the LVs don't exist in the wrappers.

**Comment by jsinglet** [comment]
Thanks for the fix!
